### ISSUE TITLE
Incorrect Infographic

### ISSUE THREAD

**Issue by patricoferris** [baizel/covidinfographics#11]
For the English translations the infographic under `9. School FAQ 6 (in English)` is a duplicate of `8. School FAQ 9 (in English)`. I'm guessing it should be [like the french one](https://covid19graphics.info/graphics/School%20Advice/French/9.%20School%20FAQ%206/Slide2.png) @baizel ?

**Comment by baizel** [comment]
Fixed b401054ec4e3da4d818abde6e17e71dc3f1eece8
